#!/usr/bin/env ruby

require 'thor'

class MirrorSvnGit < Thor
  default_task :mirror

  desc 'mirror LOCAL_DIR GIT_REMOTE', 'mirror branches from svn repo to a git repo'
  def mirror(local_dir, git_remote)
    Dir.chdir(local_dir) do
      `git svn fetch`

      delete_old_svn_branches(git_remote)
      push_svn_branches(git_remote)

      `git checkout master`
      `git merge remotes/trunk`
      `git push #{git_remote} master`
    end
  end

  no_commands do
    def delete_old_svn_branches(git_remote)
      svn_branches.each do |branch_name|
        svn_info = `svn info #{svn_branch_url(branch_name)}`
        if svn_info.empty?
          `git push --delete #{git_remote} #{short_svn_name(branch_name)}`
          FileUtils.rm_rf("#{Dir.pwd}/.git/svn/refs/remotes/#{short_svn_name(branch_name)}")
          FileUtils.rm_rf("#{Dir.pwd}/.git/refs/remotes/#{short_svn_name(branch_name)}")
        end
      end
    end

    def push_svn_branches(git_remote)
      svn_branches.each do |branch|
        `git push #{git_remote} #{branch}`
      end
    end

    def is_svn_branch?(branch_name)
      branch_name =~ /remotes\/[a-zA-Z\_\-]+$/
    end

    def svn_branch_url(branch_name)
      `git checkout #{branch_name}`
      `git svn info`.match(/URL: (https:\/\/\S+)/).captures[0]
    end

    def svn_branches
      `git branch -a`.split("\n").select do |branch_name|
        is_svn_branch? branch_name
      end
    end

    def short_svn_name(branch_name)
      branch_name.gsub(/\s+remotes\//, '')
    end
  end
end

MirrorSvnGit.start(ARGV)
